name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Deploy to Hosting
      uses: actions/setup-python@v3
      with:
          server: ${{ secrets./elicta7e.beget.tech}}
          username: ${{ secrets.elicta7e_2310 }}
          password: ${{ secrets.Elicta2310! }}
          server-dir: elicta7e.beget.tech/
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

