name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run command on remote server
      uses: tiyee/action-ssh@release
      with:
        host: ${{secrets.HOST}}
        user: ${{secrets.USERNAME}}
        private_key: ${{secrets.KAY_PUBLIC}}
        command: |
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout main;
            git pull;
