name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:

    - name: Run command on remote server
      uses: nekiro/ssh-job@main
      with:
        host: ${{elicta7e.beget.tech}}
        key: ${{ secrets.KEY_PRIVAT }}
        user: ${{elicta7e}}
        password: ${{elicta2310}}
        command: |
            cd elicta7e.beget.tech;
            git checkout main;
            git pull;
